# Generated by Django 6.0.7 on 2026-08-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
