# Generated by Django 6.0.7 on 2026-07-25 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_notes_course_notes_enabled_course_subtitle_and_more'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(blank=True, help_text='Per-lesson quiz. Passing it (>= passing_score_percent) unlocks the next lesson.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited attempts until pass'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score_percent',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
