# Generated by Django 6.0.7 on 2026-07-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Ethiopian Startup School', max_length=255)),
                ('tagline', models.CharField(blank=True, default='Learn to build. Build to grow.', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('address', models.CharField(default='Addis Ababa, Ethiopia', max_length=255)),
                ('phone', models.CharField(default='+251 94 188 3746', max_length=50)),
                ('support_email', models.EmailField(default='tilahunalenee@gmail.com', max_length=254)),
                ('bank_name', models.CharField(default='Commercial Bank of Ethiopia (CBE)', max_length=255)),
                ('bank_account_name', models.CharField(default='Commercial Bank of Ethiopia', max_length=255)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=100)),
                ('telebirr_number', models.CharField(default='+251941883746', max_length=50)),
                ('email_sender_name', models.CharField(default='Ethiopian Startup School', max_length=255)),
                ('email_verification_subject', models.CharField(default='Verify your email for Ethiopian Startup School', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
