# Generated by Django 6.0.7 on 2026-08-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_label',
            field=models.CharField(blank=True, default='Explore courses', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_url',
            field=models.CharField(blank=True, default='/courses', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Learn entrepreneurship, AI, and business skills with practical guidance from industry experts.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, default='AI Tutor, Mentor & Business Coach included', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
