# Generated by Django 6.0.7 on 2026-08-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings_hero_cta_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('site_settings', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='hero_images', to='site_settings.sitesettings')),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name': 'Hero image',
                'verbose_name_plural': 'Hero images',
            },
        ),
    ]
