# Generated by Django 6.0.7 on 2026-07-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.TextField(blank=True, help_text='Rich text course notes shown to students'),
        ),
        migrations.AddField(
            model_name='course',
            name='notes_enabled',
            field=models.BooleanField(default=False, help_text='Toggle: show the notes card to students'),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='source_url',
            field=models.URLField(blank=True, help_text='Pasted external URL for PDF/slides/other hosted files'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Rich text/HTML from the course-builder editor'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_text',
            field=models.TextField(blank=True, help_text='Rich text/HTML for text/interactive HTML lessons'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, help_text='Directly uploaded PDF/PPTX/audio file', null=True, upload_to='lesson_files/'),
        ),
    ]
