from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from html import escape

from accounts.models import User
from courses.models import Category, Course, Section, Lesson, Resource
from quizzes.models import Choice, Question, Quiz


def build_answer_choices(correct_answer, distractors, question_order):
    """Return answer choices with the correct answer placed at a rotated letter slot."""
    choices = [correct_answer, *distractors]
    target_position = (question_order - 1) % len(choices)
    if target_position == 0:
        return choices

    correct_text = choices[0]
    remaining = choices[1:]
    return remaining[:target_position] + [correct_text] + remaining[target_position:]


LESSONS = [
    {
        'section': 'Week 1: Day 1',
        'title': 'Day 1: What is a Startup? Characteristics and Myths',
        'video_url': 'https://youtu.be/mpfSiRkOk6A',
        'notes': 'Introduction\nA startup is an organization created to search for a repeatable and scalable business model under conditions of uncertainty. It is different from a small business because it usually emphasizes innovation, experimentation, and potential for rapid growth.\n\nCharacteristics\nInnovation may be technological, social, operational, or business-model based. Startups commonly work with uncertainty, iterate quickly, pursue scalable delivery, and use evidence to decide whether to persist or pivot. Their culture often values collaboration, learning, and responsible risk-taking.\n\nMyths to challenge\nStartups are not glamorous overnight successes, they do not always need venture capital, they are not limited to technology, they are not only for young founders, and failure is not automatically the end. Sustainable progress comes from customer evidence, disciplined learning, and resilience.\n\nActivity\nWrite one paragraph distinguishing a startup from a conventional small business. List three assumptions about your idea that require evidence.\n\nVideo script\nDefine startup in plain language, compare a scalable startup with a local small business, and close by separating common media myths from the daily reality of experimentation and uncertainty.',
        'questions': [('What should come before designing a solution?', 'Understanding a meaningful customer problem', ['Choosing a logo', 'Renting an office', 'Writing a long business plan']), ('Which interview evidence is strongest?', 'A repeated problem and a current workaround described by real customers', ['A founder assumption', 'A social-media like', 'A competitor slogan'])],
    },
    {
        'section': 'Week 1: Day 2',
        'title': 'Day 2: Evolution of the Indian and Global Startup Ecosystem',
        'video_url': 'https://youtu.be/huAKhDJK9nA',
        'notes': 'Introduction\nA startup ecosystem is the connected network of entrepreneurs, investors, policymakers, universities, incubators, accelerators, mentors, and service providers that enables ventures to form and grow.\n\nGlobal evolution\nIndustrial entrepreneurship, post-war research, Silicon Valley, the internet boom, and global digital connectivity each shaped modern startup ecosystems. The dot-com crash also demonstrated why growth must be supported by viable models and evidence.\n\nIndian evolution\nIndia moved from established family businesses and early information-technology services through liberalization, e-commerce, digital payments, Startup India, DPIIT recognition, and incubation programs. Its experience shows the value of policy, talent, infrastructure, and large local markets while also exposing regional and funding gaps.\n\nActivity\nMap five ecosystem actors that could support an Ethiopian startup and explain the resource each contributes.\n\nVideo script\nTrace the evolution of global ecosystems, compare the Indian journey with Ethiopia’s context, and explain why founders need relationships across capital, talent, policy, research, and markets.',
        'questions': [('What is the purpose of customer discovery?', 'To learn how people experience a problem and what they value', ['To convince people to buy immediately', 'To avoid speaking with customers', 'To finalize a company name']), ('A useful value proposition identifies what?', 'A customer, a job or problem, and a differentiated outcome', ['Only a color palette', 'Only the founder biography', 'Only a legal structure'])],
    },
    {
        'section': 'Week 1: Day 3',
        'title': 'Day 3: Types of Startups: Tech, Social, Lifestyle, Deep-Tech, Fintech',
        'video_url': 'https://youtu.be/46lr16Jc6WI',
        'notes': 'Introduction\nStartups are not one category. Their type reflects the problem they solve, the technology they use, the growth ambition they pursue, and the kind of impact they measure.\n\nTypes\nTech startups use software or digital platforms and often scale through low marginal distribution costs. Social startups combine financial sustainability with measurable social or environmental impact. Lifestyle startups prioritize founder independence, craft, and sustainable income. Deep-tech startups depend on scientific or engineering breakthroughs, research, and longer development cycles. Fintech startups use technology to improve financial services and must pay close attention to trust, security, and regulation.\n\nEthiopian application\nAn agritech, education, health, climate, creative, or financial venture may fit more than one category. Classification should clarify the model, risks, partners, and evidence required rather than become a label for publicity.\n\nActivity\nClassify your idea, state the reason, and list the special capability or regulatory consideration it requires.\n\nVideo script\nIntroduce the five startup types with examples, show where categories overlap, and help learners choose a useful classification for planning and communication.',
        'questions': [('What is a substitute?', 'Another way customers solve the same underlying job', ['Only a company with the same name', 'A government certificate', 'A founder presentation']), ('What makes a market estimate credible?', 'Clear assumptions connected to evidence and a reachable customer segment', ['A very large number alone', 'A copied competitor claim', 'An unexplained percentage'])],
    },
    {
        'section': 'Week 1: Day 4',
        'title': 'Day 4: Government Initiatives and Startup Support',
        'video_url': 'https://youtu.be/XocNvRBrPvY',
        'notes': 'Introduction\nGovernments influence startup ecosystems through policy, institutions, funding, infrastructure, procurement, research, and regulation. Government initiatives should be studied as programs with eligibility rules and current procedures, not assumed benefits.\n\nCase focus\nStartup India supports entrepreneurship through recognition, simplification, funding, incubation, market access, and partnerships. DPIIT provides an institutional recognition and policy framework. Atal Innovation Mission and Atal Incubation Centers support innovation, infrastructure, mentoring, and regional participation.\n\nCritical view\nPrograms can widen access, but founders still need to verify current eligibility, application steps, tax treatment, and local requirements with official authorities. Lessons from India can inform Ethiopian ecosystem design without being treated as Ethiopian law.\n\nActivity\nCompare one public startup-support program with one Ethiopian institution or program. Record the source, target beneficiary, benefit, and verification question.\n\nVideo script\nExplain how government programs can reduce barriers, compare Startup India, DPIIT, and Atal Incubation, and teach learners to verify every policy claim before relying on it.',
        'questions': [('What is the best use of a business model canvas?', 'Making linked business assumptions visible and testable', ['Replacing customer conversations', 'Guaranteeing funding', 'Registering a company']), ('Which assumption should be tested first?', 'The assumption that is both risky and important to viability', ['The easiest assumption', 'The least relevant detail', 'The font choice'])],
    },
    {
        'section': 'Week 1: Day 5',
        'title': 'Day 5: Startup vs Small Business and Ecosystem Mentors',
        'video_url': 'https://youtu.be/X2dgULFua-U',
        'notes': 'Case study\nA startup usually searches for a repeatable, scalable model under uncertainty. A small business often serves a defined market with a stable model and prioritizes continuity, customer trust, and sustainable income. Neither path is automatically better; the right choice depends on the founder’s goals and the problem.\n\nEcosystem builders and mentors\nEcosystem builders connect institutions, resources, and communities. Incubator mentors work more directly with founders on customers, products, teams, finance, and decisions. A useful mentor brings evidence, context, challenge, and relevant networks rather than promises of guaranteed success.\n\nActivity\nCompare a startup and a small business serving a similar Ethiopian customer group. Identify their different funding, growth, risk, and operating choices. Prepare three questions for an ecosystem builder or incubator mentor.\n\nVideo script\nUse a practical case to distinguish startup and small-business paths, then explain how ecosystem builders and mentors help founders move from theory to informed action.',
        'questions': [('What makes an MVP useful?', 'It tests a critical assumption with limited effort and a defined learning measure', ['It contains every possible feature', 'It hides manual work from users', 'It avoids measuring outcomes']), ('What should an experiment include?', 'A hypothesis, test method, metric, and decision rule', ['Only a slogan', 'Only a launch date', 'Only a budget'])],
    },
    {
        'section': 'Week 1: Day 6 - Teams and Operations',
        'title': 'Building the founding team and operating rhythm',
        'video_url': 'https://www.youtube.com/watch?v=lw2X3PxKlAY',
        'notes': 'Learning goals\nBy the end of this lesson, you should be able to define founding roles, identify capability gaps, create a decision rhythm, and design an operating system that supports learning without unnecessary bureaucracy.\n\nFounding-team design\nA strong founding team is not simply a collection of impressive CVs. It combines the capabilities required for the next milestone: understanding customers, building and delivering the product, selling or distributing it, managing money, and making sound decisions. Start by listing the next six months of critical work. Mark each responsibility as owned, shared, or missing. Avoid vague ownership such as “everyone”; one person should be accountable even when several people contribute.\n\nWorking agreements\nWrite down how the team makes decisions, handles disagreement, shares information, protects customer data, gives feedback, and responds when a commitment is missed. Discuss founder equity and decision rights with qualified legal and financial advisers before relying on an agreement. A written working agreement is a tool for clarity, not a substitute for professional advice.\n\nOperating rhythm\nUse a weekly review with five questions: What did we learn? What changed in customer behavior? Which metric matters this week? What is blocked? What decision is needed? Keep a visible decision log and a short experiment backlog. This creates accountability while preserving the speed that early ventures need.\n\nHiring and partners\nDo not hire for status. Hire or contract to remove the bottleneck that threatens the next milestone. Define the outcome, evidence of capability, trial scope, supervision, and budget. For Ethiopia, consider local talent development, remote collaboration, language access, and reliable service providers as part of the operating design.\n\nEthics and resilience\nGrowth never justifies misleading customers, hiding important limitations, exploiting workers, or mishandling personal data. Build a basic risk register covering safety, privacy, fraud, service continuity, and financial controls.\n\nActivity\nCreate a responsibility map for your venture, a weekly operating agenda, three working agreements, and a capability-gap plan. Ask one potential teammate what would make the collaboration sustainable.\n\nVideo script\nIntroduce the idea of a team as an operating system, demonstrate a responsibility map and decision log, role-play a disagreement, and close with a practical first-hire scorecard.\n\nFurther learning\nPublic reference: https://www.startupschool.org/ - see the Startup School topic “How to Lead Teams” by Ali Rowghani. This reference is not copied into this course; use it as supplementary viewing and verify its current availability.',
        'questions': [('Why define ownership in an early team?', 'To make decisions and accountability clear', ['To prevent collaboration', 'To avoid customer feedback', 'To guarantee investment']), ('A first hire should usually address what?', 'The most important capability bottleneck for the next milestone', ['The most impressive title', 'A random preference', 'Only office decoration'])],
    },
    {
        'section': 'Week 1: Day 7 - Finance and Funding',
        'title': 'Financial planning and funding strategy',
        'video_url': 'https://www.youtube.com/watch?v=9qWZALyGSmg',
        'notes': 'Learning goals\nBuild a simple cash model, understand runway and unit economics, compare funding instruments, prepare for investor questions, and choose funding that matches the venture’s stage and risk.\n\nMoney model\nSeparate operating assumptions from accounting results. List customer segments, expected customers, price, collection timing, variable cost per customer, fixed monthly costs, one-time costs, taxes and fees that have been verified for your situation, and hiring or contractor costs. Revenue is not cash until it is collected. A profitable-looking forecast can still fail when customers pay late or costs arrive early.\n\nUnit economics\nFor each important customer type, estimate contribution margin: revenue collected minus costs that rise with that customer. Track acquisition cost, activation, repeat use, retention, and payback period only when you have enough evidence to estimate them. Label every number as observed, quoted, assumed, or a target. This makes the model useful for decisions instead of presenting false precision.\n\nRunway and scenarios\nRunway is the number of months current cash can support planned net spending. Create conservative, base, and upside scenarios. Add a cash buffer for delays and unexpected costs. Review the model weekly during a funding or launch period, and record which assumption changed.\n\nFunding choices\nRevenue, bootstrapping, grants, debt, angel investment, venture capital, strategic partnerships, and competitions have different costs and obligations. Debt creates repayment risk. Equity changes ownership and governance. Grants may have eligibility, reporting, and use restrictions. Do not promise an investor return or claim eligibility for a government program without checking current official requirements and obtaining professional advice where needed.\n\nInvestor readiness\nA credible funding conversation explains the problem, evidence, product, traction, market, model, team, risks, amount requested, and milestone the money will finance. Maintain a clean data room with incorporation records, contracts, financial statements, cap table, intellectual property records, and key metrics, shared only with appropriate safeguards.\n\nActivity\nBuild a 12-month monthly cash-flow table with three scenarios. Circle the three assumptions that most affect survival. Write the next measurable milestone that funding would achieve and the evidence that would show progress.\n\nVideo script\nBuild a simple cash forecast on screen, explain revenue versus cash and contribution margin, compare funding choices, and show how a founder answers “What will this money change?” without exaggeration.\n\nFurther learning\nPublic reference: https://www.startupschool.org/ - see “Modern Startup Funding” by Carolynn Levy. This is supplementary viewing, not reproduced course content.',
        'questions': [('What does runway describe?', 'How long available cash can support planned operations under stated assumptions', ['The number of customers forever', 'A legal license period', 'The company logo']), ('What should funding enable?', 'A specific milestone that reduces meaningful business risk', ['Only a larger office', 'Unmeasured spending', 'Avoiding financial records'])],
    },
    {
        'section': 'Week 1: Day 8 - Go-to-Market and Pitch',
        'title': 'Launch, growth, and the investor story',
        'video_url': 'https://www.youtube.com/watch?v=T9ikpoF2GH0',
        'notes': 'Learning goals\nCreate a focused go-to-market plan, choose a realistic first channel, define activation and retention measures, prepare a clear five-minute pitch, and launch with responsible claims and feedback loops.\n\nTarget and positioning\nBegin with a narrow segment that has a recognizable need and a reason to act now. Positioning answers: For whom is this? What job or problem does it address? What alternative do customers use today? Why is this approach meaningfully different? Test the language with customers; do not assume a clever slogan is a strategy.\n\nChannel and sales motion\nChoose channels based on where the target customer already makes decisions. Options may include direct sales, community partnerships, universities, cooperatives, marketplaces, referrals, content, demonstrations, or a self-serve digital flow. Define the first contact, qualification question, offer, payment or commitment step, onboarding, and follow-up. For Ethiopian markets, consider trust, language, connectivity, payment preferences, geography, and partner relationships.\n\nLaunch loop\nSet a weekly growth loop: attract a qualified visitor, help them understand the value, make the first action easy, deliver the promised outcome, ask for feedback, and encourage appropriate repeat use or referral. Track a small set of measures: qualified leads, activation, conversion, repeat use, retention, revenue collected, and support issues. Never buy misleading engagement or hide negative evidence.\n\nPitch structure\nA useful pitch can follow this sequence: customer problem; evidence; current alternatives; solution demonstration; why now; market and reachable segment; business model; traction; go-to-market; team; risks; funding request; milestone plan. Use one idea per slide, readable numbers, source notes, and an honest distinction between actual results and forecasts.\n\nCapstone\nSubmit a validated problem statement, five customer evidence notes, competitor table, Business Model Canvas, MVP experiment results, 12-month financial model, one-page go-to-market plan, and a five-minute pitch. Include three risks and how you will test or reduce them.\n\nActivity\nChoose one launch segment, one primary channel, and one measurable activation event. Draft a two-week launch experiment with owner, budget, daily actions, success threshold, stop rule, and customer-protection considerations.\n\nVideo script\nDemonstrate positioning with a local example, map a customer journey from discovery to repeat use, review a sample dashboard, then deliver and critique a five-minute pitch using evidence rather than hype.\n\nFurther learning\nPublic reference: https://www.startupschool.org/ - see “How to Get Users and Grow” by Gustaf Alstromer and “How to Launch your Company in the Press” by Kat Manalac. These are supplementary public references and are not copied into this course.',
        'questions': [('What should a go-to-market plan connect?', 'A target customer, positioning, channel, sales or onboarding motion, and measurable goals', ['Only a launch party', 'Only a company name', 'Only a funding request']), ('What makes a pitch credible?', 'A clear story supported by customer evidence, assumptions, milestones, and an honest ask', ['Only confident speaking', 'Only a large market number', 'Only visual effects'])],
    },
]


def format_lesson_notes(text):
    headings = {'Introduction', 'Learning goals', 'Characteristics', 'Myths to challenge', 'Global evolution', 'Indian evolution', 'Types', 'Ethiopian application', 'Case study', 'Ecosystem builders and mentors', 'Founding-team design', 'Working agreements', 'Operating rhythm', 'Hiring and partners', 'Ethics and resilience', 'Money model', 'Unit economics', 'Runway and scenarios', 'Funding choices', 'Investor readiness', 'Target and positioning', 'Channel and sales motion', 'Launch loop', 'Pitch structure', 'Capstone', 'Activity', 'Video script', 'Further learning', 'Critical view'}
    output = []
    for raw in text.split('\n\n'):
        lines = [line.strip() for line in raw.splitlines() if line.strip()]
        if not lines:
            continue
        heading = lines[0]
        body = ' '.join(lines[1:])
        if heading in headings:
            if heading == 'Activity':
                output.append(f'<aside class="learning-callout"><strong>Practice activity</strong><p>{escape(body)}</p></aside>')
            elif heading == 'Video script':
                output.append(f'<aside class="learning-callout"><strong>Video lesson guide</strong><p>{escape(body)}</p></aside>')
            elif heading == 'Further learning':
                output.append(f'<p><strong>Further learning:</strong> {escape(body)}</p>')
            else:
                output.append(f'<h2><strong><em>{escape(heading)}</em></strong></h2>')
                if body:
                    output.append(f'<p>{escape(body)}</p>')
        else:
            output.append(f'<p>{escape(" ".join(lines))}</p>')
    return ''.join(output)


EXTRA_QUESTIONS = {
    1: [('What is the main purpose of a startup?', 'To search for a repeatable and scalable model under uncertainty', ['To copy an established business exactly', 'To avoid testing assumptions', 'To guarantee immediate profit']), ('Which trait often distinguishes a startup?', 'A willingness to experiment and learn from evidence', ['Permanent certainty', 'No customer contact', 'Fixed plans that never change']), ('What does scalability mean?', 'Growth without costs increasing at the same rate', ['Hiring one person only', 'Operating without customers', 'Avoiding all technology']), ('Why can myths about startups be harmful?', 'They hide the uncertainty, effort, and risk involved', ['They improve accounting', 'They guarantee funding', 'They replace research']), ('Can a startup be non-technical?', 'Yes, innovation can occur in services, agriculture, education, or other sectors', ['No, never', 'Only after an IPO', 'Only with venture capital']), ('What is a useful first founder activity?', 'Speak with people who experience the problem', ['Choose an office', 'Design merchandise', 'Publish a valuation']), ('What does a pivot involve?', 'Changing an important assumption or direction based on learning', ['Ignoring evidence', 'Closing every business', 'Changing a logo only']), ('What should founders protect while experimenting?', 'Customer trust, safety, privacy, and honest communication', ['Only their slogan', 'Only their office furniture', 'Only their pitch color'])],
    2: [('What is an ecosystem?', 'A network of actors and institutions that support venture creation and growth', ['Only a list of companies', 'Only a funding round', 'Only a university course']), ('What helped Silicon Valley develop?', 'Research, talent, government support, networks, and venture capital', ['One founder alone', 'No institutions', 'A single retail store']), ('What lesson followed the dot-com crash?', 'Growth needs a viable model and sustainable economics', ['Revenue never matters', 'Every startup should scale instantly', 'Research is unnecessary']), ('Which was important in India’s digital growth?', 'Digital infrastructure and policies that enabled broader participation', ['Removing all customers', 'Avoiding mobile networks', 'Ending entrepreneurship']), ('Why compare ecosystems carefully?', 'Local institutions, markets, infrastructure, and policy differ', ['All ecosystems are identical', 'Comparison removes risk', 'It avoids evidence']), ('Who can be an ecosystem actor?', 'A mentor, investor, university, government body, incubator, or founder', ['Only a bank', 'Only a founder', 'Only a regulator']), ('What is a regional ecosystem challenge?', 'Support and capital may be concentrated in major cities', ['Every region has identical access', 'Distance never matters', 'Talent is irrelevant']), ('What should an ecosystem map identify?', 'The resource each actor contributes and the gap that remains', ['Only logos', 'Only office locations', 'Only media coverage'])],
    3: [('What defines a social startup?', 'It combines entrepreneurial activity with measurable social or environmental impact', ['It avoids all revenue', 'It must be a public company', 'It only sells software']), ('Why do deep-tech startups often need more time?', 'Scientific development, testing, and validation can take longer', ['Customers are unnecessary', 'They never use research', 'They avoid prototypes']), ('What is a fintech risk?', 'Trust, security, and compliance requirements', ['No customer risk', 'No regulation anywhere', 'Only office rent']), ('What often motivates a lifestyle startup?', 'Sustainable founder income and work aligned with personal interests', ['Guaranteed unicorn status', 'A public listing', 'No customers']), ('Can categories overlap?', 'Yes, one venture can be technology-enabled and socially focused', ['Never', 'Only after acquisition', 'Only outside Ethiopia']), ('What should classification help a founder understand?', 'Capabilities, risks, partners, and evidence required', ['Only a marketing slogan', 'Only a logo', 'Only a tax rate']), ('What is a tech startup advantage?', 'Digital distribution may scale with relatively low marginal cost', ['It has no costs', 'It needs no users', 'It avoids data responsibility']), ('What is important in impact ventures?', 'Measure outcomes as well as financial sustainability', ['Ignore outcomes', 'Track publicity only', 'Avoid beneficiaries'])],
    4: [('What is Startup India?', 'A government initiative supporting entrepreneurship and innovation in India', ['An Ethiopian tax law', 'A private bank', 'A university exam']), ('What role does DPIIT play?', 'Policy and recognition support within India’s startup framework', ['It runs every startup', 'It replaces customers', 'It is a venture founder']), ('What does an incubator commonly provide?', 'Infrastructure, mentoring, networks, and support', ['Guaranteed profit', 'Automatic valuation', 'No feedback']), ('Why verify program eligibility?', 'Rules, dates, benefits, and procedures can change', ['Rules never change', 'Verification is illegal', 'It guarantees acceptance']), ('What is public procurement?', 'Government purchasing of goods or services', ['A founder agreement', 'A customer interview', 'A private pitch']), ('Why can regional inclusion matter?', 'It broadens opportunity beyond established hubs', ['It removes all risk', 'It ends competition', 'It prevents innovation']), ('What is a policy limitation?', 'Access may remain uneven despite a program’s existence', ['Every founder benefits equally', 'Programs need no awareness', 'Infrastructure never matters']), ('What should Ethiopian founders do with foreign policy examples?', 'Use them as learning references, not as Ethiopian legal requirements', ['Copy them as law', 'Ignore all evidence', 'Treat them as contracts'])],
    5: [('What is a small business usually optimized for?', 'Stable service and sustainable operation in a defined market', ['Only exponential growth', 'Only venture funding', 'No customers']), ('What is a startup usually searching for?', 'A repeatable and scalable business model', ['A permanent routine', 'A fixed local monopoly', 'No evidence']), ('What does an ecosystem builder do?', 'Connects people, resources, institutions, and opportunities', ['Only sells office furniture', 'Only audits taxes', 'Only writes exams']), ('What does an incubator mentor provide?', 'Direct guidance on decisions, products, customers, teams, or funding', ['A guaranteed investment', 'A legal exemption', 'A public listing']), ('Why are both startups and small businesses valuable?', 'They contribute different forms of innovation, jobs, and continuity', ['Only startups create value', 'Only small firms matter', 'Neither serves customers']), ('What is a useful case-study comparison?', 'Compare growth, funding, risk, innovation, and market scope', ['Compare logos only', 'Compare founder age only', 'Compare office size only']), ('What makes mentorship useful?', 'Relevant experience, honest feedback, and context-aware connections', ['Promises of certainty', 'Hype only', 'No questions']), ('How can guest talks be more inclusive?', 'Use digital access and include diverse founders and regions', ['Limit them to one city', 'Exclude rural founders', 'Avoid practical examples'])],
    6: [('What should determine founding roles?', 'The capabilities required for the next important milestone', ['Founder popularity', 'Office size', 'A random title']), ('Why write working agreements?', 'To clarify decisions, feedback, conduct, and accountability', ['To prevent communication', 'To guarantee funding', 'To replace all laws']), ('What is a decision log?', 'A short record of important decisions and their reasoning', ['A customer invoice', 'A pitch slogan', 'A tax certificate']), ('What should a weekly team review ask?', 'What was learned, what changed, what is blocked, and what decision is needed', ['Who has the fanciest title', 'Which logo is best', 'How to avoid customers']), ('When is hiring justified?', 'When a specific capability bottleneck threatens the next milestone', ['Whenever a title sounds impressive', 'Before identifying work', 'Only after an IPO']), ('What should an early operating system protect?', 'Speed, accountability, customer trust, and responsible conduct', ['Confusion', 'Hidden risks', 'Unrecorded decisions']), ('Why create a risk register?', 'To identify and reduce safety, privacy, financial, and continuity risks', ['To avoid planning', 'To increase hype', 'To remove all experimentation']), ('What is complementary expertise?', 'Different capabilities that together cover important venture work', ['Identical skills only', 'Only academic degrees', 'Only investor contacts'])],
    7: [('What is the difference between revenue and cash?', 'Revenue is earned income while cash reflects when money is collected and paid', ['They are always identical', 'Cash is only equity', 'Revenue is a legal license']), ('What does contribution margin measure?', 'Revenue collected minus costs that vary with serving a customer', ['Total employees', 'Office size', 'Founder age']), ('What is runway?', 'The time current cash can support planned net spending', ['A customer segment', 'A pitch slide', 'A business license']), ('Why use multiple forecast scenarios?', 'To understand how different assumptions affect survival and decisions', ['To hide uncertainty', 'To guarantee results', 'To avoid records']), ('What is a debt obligation?', 'Repayment and related terms that remain owed under an agreement', ['Free capital with no conditions', 'An automatic grant', 'A customer interview']), ('What does equity funding change?', 'Ownership and potentially governance or future economic rights', ['Only the logo', 'Nothing contractual', 'The weather']), ('What belongs in an investor data room?', 'Relevant corporate, financial, ownership, contract, and metric records', ['Unverified rumors', 'Private passwords', 'Only marketing slogans']), ('What should a funding milestone do?', 'Reduce a meaningful business risk with measurable evidence', ['Increase spending without learning', 'Avoid customers', 'Guarantee valuation'])],
    8: [('What is positioning?', 'A clear statement of who the product helps, what problem it solves, and why it differs', ['Only a color choice', 'A tax filing', 'An office address']), ('How should a first channel be selected?', 'By where the target customer already makes decisions and can be reached', ['By popularity alone', 'By the founder’s favorite app', 'Randomly']), ('What is activation?', 'A meaningful first action showing that a user has begun receiving value', ['A press mention', 'An office opening', 'A logo change']), ('Why track retention?', 'To learn whether customers continue receiving enough value to return', ['To avoid feedback', 'To inflate a pitch', 'To replace revenue']), ('What should a five-minute pitch explain?', 'Problem, evidence, solution, market, model, traction, team, ask, and risks', ['Only the founder biography', 'Only the largest market number', 'Only a slogan']), ('Why separate targets from actual results?', 'It prevents forecasts from being presented as evidence', ['It makes numbers larger', 'It avoids accountability', 'It guarantees investment']), ('What is a launch experiment?', 'A bounded test with an owner, actions, metric, threshold, and stop rule', ['An unlimited campaign', 'A funding promise', 'A company registration']), ('What makes growth responsible?', 'Honest claims, customer protection, measurable learning, and sustainable economics', ['Buying fake engagement', 'Hiding risks', 'Ignoring support issues'])],
}


class Command(BaseCommand):
    help = 'Create or refresh the original Startup Fundamentals: From Idea to Launch course.'

    def add_arguments(self, parser):
        parser.add_argument('--instructor', help='Instructor username or numeric user id.')
        parser.add_argument('--dry-run', action='store_true')

    def handle(self, *args, **options):
        instructor = self._get_instructor(options.get('instructor'))
        if any(len(item['questions']) + len(EXTRA_QUESTIONS.get(index, [])) != 10 for index, item in enumerate(LESSONS, start=1)):
            raise CommandError('Every lesson must contain exactly ten questions.')
        if options['dry_run']:
            self.stdout.write(self.style.SUCCESS(f'Validated {len(LESSONS)} lessons and {len(LESSONS) * 10} questions.'))
            return
        with transaction.atomic():
            category, _ = Category.objects.get_or_create(slug='startup', defaults={'name': 'Startup'})
            course, _ = Course.objects.update_or_create(slug='startup-fundamentals-idea-to-launch', defaults={
                'title': 'Startup Fundamentals: From Idea to Launch',
                'subtitle': 'An original, practical 8-week startup-building course',
                'description': 'An original course helping aspiring entrepreneurs move from problem discovery to a tested MVP, responsible funding plan, and launch pitch. Inspired by the public course overview at https://onlinecourses.swayam2.ac.in/e-learning/course/imb26_mg119, but all lesson materials here are newly written for Ethiopian Startup School.',
                'short_description': 'Turn a real customer problem into a tested startup plan.',
                'notes': '<h2>Course study guide</h2><p>Complete one weekly lesson, its activity, and its quiz. The final capstone combines your evidence into a launch-ready portfolio.</p><p><strong>Source note:</strong> The public SWAYAM course page was used only as high-level inspiration for the 8-week topic sequence. This course does not reproduce its videos or lesson text.</p>',
                'notes_enabled': True,
                'learning_objectives': 'Identify and validate customer problems; research markets and competitors; build a Business Model Canvas; design an MVP experiment; plan operations, finance, funding, go-to-market, and a concise pitch.',
                'requirements': 'No prior startup experience required. Access to three potential customer conversations is recommended.',
                'target_audience': 'Students, aspiring founders, innovators, and early-stage business professionals.',
                'tags': 'startup, entrepreneurship, MVP, market research, business model, funding, pitch',
                'instructor': instructor, 'category': category, 'level': Course.Level.BEGINNER,
                'status': Course.Status.PUBLISHED, 'price': 0, 'is_free': True, 'language': 'English', 'duration_hours': 16,
            })
            for order, item in enumerate(LESSONS, start=1):
                section, _ = Section.objects.update_or_create(course=course, order=order, defaults={'title': item['section']})
                lesson, _ = Lesson.objects.update_or_create(section=section, order=1, defaults={
                    'title': item['title'], 'lesson_type': Lesson.LessonType.VIDEO,
                    'content_text': format_lesson_notes(item['notes']), 'video_url': item.get('video_url', ''), 'source_url': item.get('source_url', ''), 'duration_minutes': 60, 'is_preview': order == 1,
                    'is_downloadable': True,
                })
                # The lesson video is the primary video. Admins can add any number
                # of additional Resource records from the lesson admin inline.
                Resource.objects.filter(lesson=lesson, title='Original instructor video').delete()
                quiz, _ = Quiz.objects.update_or_create(lesson=lesson, defaults={
                    'course': course, 'section': section, 'title': f'{item["title"]} Quiz', 'passing_score_percent': 80,
                })
                quiz.questions.all().delete()
                questions = item['questions'] + EXTRA_QUESTIONS.get(order, [])
                for question_order, (question_text, answer, distractors) in enumerate(questions, start=1):
                    question = Question.objects.create(quiz=quiz, text=question_text, question_type=Question.QuestionType.MULTIPLE_CHOICE, order=question_order)
                    answer_choices = build_answer_choices(answer, distractors, question_order)
                    for choice_order, choice_text in enumerate(answer_choices):
                        Choice.objects.create(question=question, text=choice_text, is_correct=choice_text == answer, order=choice_order)
        self.stdout.write(self.style.SUCCESS(f'Created course {course.title} (id={course.id}) with 8 video-script lessons and 80 quiz questions.'))

    def _get_instructor(self, identifier):
        queryset = User.objects.filter(role=User.Role.INSTRUCTOR)
        if identifier:
            try:
                return queryset.get(pk=identifier)
            except (User.DoesNotExist, ValueError):
                user = queryset.filter(username=identifier).first()
                if user:
                    return user
            raise CommandError(f'Instructor not found: {identifier}')
        user = queryset.order_by('id').first()
        if not user:
            raise CommandError('No instructor exists. Create an instructor or pass --instructor.')
        return user
