# Generated by Django 5.2.3 on 2026-10-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(upload_to='news/')),
                ('image_alt_text', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('author', models.CharField(default='Ethiopian Startup School', max_length=160)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['-is_published', '-published_at'], name='news_pub_date_idx')],
            },
        ),
    ]
